# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-pvc
  namespace: logging
spec:
  storageClassName: myloggingstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-storage
spec:
  storageClassName: myloggingstorage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/logging"
    type: DirectoryOrCreate
